# .github/workflows/git-sync.yml

on: push
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "nextgentravel/estimator-build"
          source_branch: "main"
          destination_repo: "${{ secrets.DESTINATION_REPO }}"
          destination_branch: "main"
          destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }}