name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - user-testing
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - user-testing

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    env:
      # GA_TRACKING_ID: "UA-173947223-2"
      HOTJAR_ID: "1974954"
      HOTJAR_SNIPPET_VERSION: "6"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          app_build_command: "GA_TRACKING_ID=${{env.GA_TRACKING_ID}} HOTJAR_ID=${{env.HOTJAR_ID}} HOTJAR_SNIPPET_VERSION=${{env.HOTJAR_SNIPPET_VERSION}} npm run build"
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DELIGHTFUL_MEADOW_054785B10 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "api" # Api source code path - optional
          app_artifact_location: "public" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DELIGHTFUL_MEADOW_054785B10 }}
          action: "close"