name: Build gatsby and push to remote prod repo

on:
  push:
    branches:
      - gc-prod

jobs:
  build-and-deploy:
    name: Build and deploy Gatsby site
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          path: standalone-estimator
      
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'

      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli@2.18.0

      - name: Install yarn
        run: npm install -g yarn

      - name: Install Project Dependencies
        run: cd standalone-estimator && yarn
      
      - name: Build
        run: cd standalone-estimator && gatsby build
      
      - name: Verify build
        run: ls -la standalone-estimator/public

      - name: Checkout Build Repo
        uses: actions/checkout@v2
        with:
          repository: nextgentravel/gc-prod-build
          token: ${{ secrets.PUSH_TO_BUILD }} # `GitHub_PAT` is a secret that contains your PAT
          path: gc-prod-build
      - run: |
          cp -RT standalone-estimator/public gc-prod-build
          mkdir -p gc-prod-build/.github/workflows && cp standalone-estimator/buildworkflow.yml gc-prod-build/.github/workflows
          cd gc-prod-build
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Deployed ${{ steps.date.outputs.date }}"
          git push



      # - name: Push build to private repo
      #   run: |
      #     git remote set-url origin https://github.com/nextgentravel/gc-prod-build.git
      #     mkdir public gc-prod-build
      #     touch public/index.html
      #     cp -RT public gc-prod-build
      #     cd gc-prod-build
      #     git config --local user.name "github-actions[bot]"
      #     git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
      #     git add -A
      #     git commit -m "Updated build"
      #     git push https://$USERNAME:$REPO_KEY@github.com/nextgentravel/gc-prod-build.git
      #   env:
      #     REPO_KEY: ${{secrets.PUSH_TO_BUILD}}
      #     USERNAME: github-actions[bot]