name: build

on:
  push:
    branches:
      - build-to-azure

jobs:
  build-and-deploy:
    name: Build and deploy Gatsby site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # persist-credentials: false
          path: standalone-estimator
          # submodules: false
      
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'

      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli@2.18.0

      - name: Install yarn
        run: npm install -g yarn

      - name: Install Project Dependencies
        run: cd standalone-estimator && yarn
      
      - name: Build
        run: cd standalone-estimator && gatsby build
      
      - name: Verify build
        run: ls -la standalone-estimator/public

      - name: Checkout Build Repo
        uses: actions/checkout@v2
        with:
          repository: nextgentravel/estimator-build
          token: ${{ secrets.PUSH_TO_BUILD }} # `GitHub_PAT` is a secret that contains your PAT
          path: estimator-build
      - run: |
          cp -RT standalone-estimator/public estimator-build
          cd ../estimator-build
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push



      # - name: Push build to private repo
      #   run: |
      #     git remote set-url origin https://github.com/nextgentravel/estimator-build.git
      #     mkdir public estimator-build
      #     touch public/index.html
      #     cp -RT public estimator-build
      #     cd estimator-build
      #     git config --local user.name "github-actions[bot]"
      #     git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
      #     git add -A
      #     git commit -m "Updated build"
      #     git push https://$USERNAME:$REPO_KEY@github.com/nextgentravel/estimator-build.git
      #   env:
      #     REPO_KEY: ${{secrets.PUSH_TO_BUILD}}
      #     USERNAME: github-actions[bot]