name: Review App Test

on:
    pull_request:
        branches:
        - docker

jobs:
  review-app-test:

    runs-on: ubuntu-latest
    
    steps:
    - name: Run review-app test
      id: review_app_test  # `id` value is used to refer the outputs from the corresponding action 
      uses: niteoweb/reviewapps-deploy-status@v1.4.0
      env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      with:
        # Checks to be performed, default is all the checks
        checks: build, response

        # Delay for the application to be built in Heroku, default is 5 seconds
        build_time_delay: 5

        # Delay for the application to load and start serving, default is 5 seconds
        load_time_delay: 5

        # Interval for the repeating checks, default is 10 seconds
        interval: 10

        # Acceptable responses for the response check, default is 200
        accepted_responses: 200

        # Max time to be spent retrying for the build check, default is 120
        deployments_timeout: 120

        # Max time to be spent retrying for the response check, default is 120
        publish_timeout: 120

    # `steps.review_app_test.outputs.review_app_url` must be used in workflow to fetch the Review App URL 
    - name: Check review_app_url
      run: |
        echo "Outputs :"
        echo "- App name: ${{ steps.review_app_test.outputs.review_app_name }}"
        echo "- App url: ${{ steps.review_app_test.outputs.review_app_url }}"
