name: Deploy to Heroku
  env:
    HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_KEY }}
    HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
  if: github.ref == 'refs/heads/master' && job.status == 'success'
  run: git push https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git origin/master:master

name: Gatsby Publish
on:
  deployment_status
jobs:
  build:
    name: a11y
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: docker://cdssnc/a11y-multiple-page-checker
      uses: docker://cdssnc/a11y-multiple-page-checker
